typeR = {
    'add': { 'opcode': '000000', 'format': ['rd','rs','rt'] },
    'addu': { 'opcode': '000011', 'format': ['rd','rs','rt'] },
    'clo': { 'opcode': '000100', 'format': ['rd', 'rs'] },
    'clz': { 'opcode': '000101', 'format': ['rd', 'rs'] },
    'sub': { 'opcode': '000110', 'format': ['rd', 'rs', 'rt'] },
    'subu': { 'opcode': '000111', 'format': ['rd', 'rs', 'rt'] },
    'seb': { 'opcode': '001000', 'format': ['rd', 'rs'] },
    'seh': { 'opcode': '001001', 'format': ['rd', 'rs'] },
    'neg': { 'opcode': '001011', 'format': ['rd', 'rs'] },
    'sll': { 'opcode': '001100', 'format': ['rd','rs','shift'] },
    'sllv': { 'opcode': '001101', 'format': ['rd','rs','rt'] },
    'sra': { 'opcode': '001110', 'format': ['rd', 'rs', 'shift'] },
    'srav': { 'opcode': '001111', 'format': ['rd', 'rs', 'rt'] },
    'srl': { 'opcode': '010000', 'format': ['rd', 'rs', 'shift'] },
    'srlv': { 'opcode': '010001', 'format': ['rd', 'rs', 'rt' ] },
    'and': { 'opcode': '010010', 'format': ['rd','rs','rt'] },
    'nor': { 'opcode': '010100', 'format': ['rd','rs','rt'] },
    'or': { 'opcode': '010101', 'format': ['rd', 'rs', 'rt'] },
    'xor': { 'opcode': '010111', 'format': ['rd', 'rs', 'rt'] },
    'not': { 'opcode': '011001', 'format': ['rd','rs'] },
    'nand': { 'opcode': '011010', 'format': ['rd', 'rs', 'rt'] },
    'div': { 'opcode': '011100', 'format': ['rs','rt'] },
    'divu': { 'opcode': '011110', 'format': ['rs','rt'] },
    'madd': {'opcode': '011111', 'format': ['rs','rt'] },
    'maddu': { 'opcode': '100000', 'format': ['rs', 'rt'] },
    'msub': { 'opcode': '100001', 'format': ['rs', 'rt'] },
    'msubu': { 'opcode': '100010', 'format': ['rs', 'rt'] },
    'mul':  { 'opcode': '100011', 'format': ['rd','rs','rt'] },
    'mulu': { 'opcode': '100101', 'format': ['rd','rs','rt'] },
    'mult': { 'opcode': '100110', 'format': ['rs','rt'] },
    'multu': {'opcode': '100111', 'format': ['rs','rt'] },
    'mfhi': { 'opcode': '101000', 'format': ['rd'] },
    'mflo': { 'opcode': '101001', 'format': ['rd'] },
    'mthi': { 'opcode': '101010', 'format': ['rs'] },
    'mtlo': { 'opcode': '101011', 'format': ['rs'] },
    'jr': { 'opcode': '110001', 'format': ['rs'] },
    'movn': { 'opcode': '111010', 'format': ['rd','rs','rt'] },
    'movz': { 'opcode': '111011', 'format': ['rd','rs','rt'] },
    'slt': { 'opcode': '111100', 'format': ['rd','rs','rt'] },
    'sltu': { 'opcode': '111111', 'format': ['rd','rs','rt'] },
    'jalr': { 'opcode': '110011', 'format': ['rd', 'rs'] }
}
